/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemadeactivos.presentation.jeferrhh.personal.listado;

import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author xxxx
 */
public class PersonalsView extends javax.swing.JInternalFrame implements Observer{
    PersonalsController controller;
    PersonalsModel model;
    
    public PersonalsView() {
        initComponents();
    }

    public PersonalsController getController() {
        return controller;
    }

    public void setController(PersonalsController controller) {
        this.controller = controller;
    }

    public PersonalsModel getModel() {
        return model;
    }

    public void setModel(PersonalsModel model) {
        this.model = model;
        model.addObserver(this);
    }

    
    @Override
    public void update(Observable o, Object arg) {
        this.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    
}
