/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemadeactivos.presentation.application;

import java.util.Observable;
import java.util.Observer;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author mauri
 */
public class ApplicationView extends javax.swing.JFrame implements Observer{

     public ApplicationView() {
        initComponents();
        this.setExtendedState(ApplicationView.MAXIMIZED_BOTH);
    }

    ApplicationController controller;
    ApplicationModel model;
    
    public void setController(ApplicationController controller){
        this.controller=controller;
    }
    

    public ApplicationController getController() {
        return controller;
    }
    
    public void setModel(ApplicationModel model){
        this.model=model;
         model.addObserver(this);
    }

    public ApplicationModel getModel() {
        return model;
    }
    
     public void addInternalFrame(JInternalFrame f){
       this.desktopPane.add(f);
   }

    @Override
    public void update(Observable o, Object arg) {
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        jefeRRHHMenu = new javax.swing.JMenu();
        dependenciasMenuItem = new javax.swing.JMenuItem();
        personalMenuItem = new javax.swing.JMenuItem();
        activosMenuItem = new javax.swing.JMenuItem();
        administradorMenu = new javax.swing.JMenu();
        ingresarMenuItem = new javax.swing.JMenuItem();
        consultarMenuItem = new javax.swing.JMenuItem();
        secretariaMenu = new javax.swing.JMenu();
        solicitudesMenu = new javax.swing.JMenuItem();
        jefeOCCBMenu = new javax.swing.JMenu();
        consultarMenuItem1 = new javax.swing.JMenuItem();
        registradorMenu = new javax.swing.JMenu();
        catalogo = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Principal");
        setLocation(new java.awt.Point(600, 300));

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );

        fileMenu.setText("Salir");

        exitMenuItem.setText("Logout");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        jMenuBar1.add(fileMenu);

        jefeRRHHMenu.setText("Jefe De RRHH");

        dependenciasMenuItem.setText("Dependencias");
        dependenciasMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dependenciasMenuItemActionPerformed(evt);
            }
        });
        jefeRRHHMenu.add(dependenciasMenuItem);

        personalMenuItem.setText("Personal");
        personalMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalMenuItemActionPerformed(evt);
            }
        });
        jefeRRHHMenu.add(personalMenuItem);

        activosMenuItem.setText("Activos");
        activosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activosMenuItemActionPerformed(evt);
            }
        });
        jefeRRHHMenu.add(activosMenuItem);

        jMenuBar1.add(jefeRRHHMenu);

        administradorMenu.setText("Administrador");

        ingresarMenuItem.setText("Ingresar Solicitud");
        ingresarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarMenuItemActionPerformed(evt);
            }
        });
        administradorMenu.add(ingresarMenuItem);

        consultarMenuItem.setText("Consultar Solicitud");
        administradorMenu.add(consultarMenuItem);

        jMenuBar1.add(administradorMenu);

        secretariaMenu.setText("Secretaria");

        solicitudesMenu.setText("Solicitudes");
        solicitudesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitudesMenuActionPerformed(evt);
            }
        });
        secretariaMenu.add(solicitudesMenu);

        jMenuBar1.add(secretariaMenu);

        jefeOCCBMenu.setText("Jefe De La OCCB");

        consultarMenuItem1.setText("Consultar Solicitud");
        jefeOCCBMenu.add(consultarMenuItem1);

        jMenuBar1.add(jefeOCCBMenu);

        registradorMenu.setText("Registrador");

        catalogo.setText("Catalogo");
        catalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catalogoActionPerformed(evt);
            }
        });
        registradorMenu.add(catalogo);

        jMenuBar1.add(registradorMenu);

        helpMenu.setText("Ayuda");

        aboutMenuItem.setText("Acerca de");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        this.controller.exit();
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        JOptionPane.showMessageDialog(this, "Sistema de Activos \n Version 1.0", "Acerca de..", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void dependenciasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dependenciasMenuItemActionPerformed
        controller.dependenciasShow();
    }//GEN-LAST:event_dependenciasMenuItemActionPerformed

    private void activosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activosMenuItemActionPerformed
        controller.catalogoShow();
    }//GEN-LAST:event_activosMenuItemActionPerformed

    private void solicitudesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitudesMenuActionPerformed
        controller.secretariaShow();
    }//GEN-LAST:event_solicitudesMenuActionPerformed

    private void personalMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalMenuItemActionPerformed
        controller.funcionarioShow();
    }//GEN-LAST:event_personalMenuItemActionPerformed

    private void ingresarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarMenuItemActionPerformed
       controller.ingresarSolicitudesShow();
    }//GEN-LAST:event_ingresarMenuItemActionPerformed

    private void catalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catalogoActionPerformed
       controller.catalogoShow();        // TODO add your handling code here:
    }//GEN-LAST:event_catalogoActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem activosMenuItem;
    private javax.swing.JMenu administradorMenu;
    private javax.swing.JMenuItem catalogo;
    private javax.swing.JMenuItem consultarMenuItem;
    private javax.swing.JMenuItem consultarMenuItem1;
    private javax.swing.JMenuItem dependenciasMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem ingresarMenuItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jefeOCCBMenu;
    private javax.swing.JMenu jefeRRHHMenu;
    private javax.swing.JMenuItem personalMenuItem;
    private javax.swing.JMenu registradorMenu;
    private javax.swing.JMenu secretariaMenu;
    private javax.swing.JMenuItem solicitudesMenu;
    // End of variables declaration//GEN-END:variables
}
